apiVersion: apps/v1
kind: Deployment
metadata:
  name: conf
  labels:
    app: conf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conf
  template:
    metadata:
      labels:
        app: conf
    spec:
      containers:
      - name: conf
        image: rvillaes/spring-boot-app:1.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: app-config
          mountPath: "/app/resources"
          readOnly: true
        - name: app-secret
          mountPath: "/app/resources/secrets"
          readOnly: true
      volumes:
      - name: app-config
        configMap:
          name: app-conf
          items:
          - key: application.properties
            path: application.properties
      - name: app-secret
        secret:
          secretName: app-secret