apiVersion: v1
kind: Service
metadata:
  name: np-service
  labels:
    app: conf
spec:
  selector:
    app: conf
  type: NodePort
  ports:
    - nodePort: 31000
      port: 8080
      targetPort: 8080