apiVersion: v1
kind: Pod
metadata:
  name: conf-demo
spec:
  containers:
  - name: test
    image: rvillaes/spring-boot-app:1.0
    volumeMounts:
    - name: app-config
      mountPath: "/app/resources"
      readOnly: true
    - name: app-secret
      mountPath: "/app/resources/secrets"
      readOnly: true
  volumes:
  - name: app-config
    configMap:
      name: app-conf
      items:
      - key: application.properties
        path: application.properties
  - name: app-secret
    secret:
      secretName: app-secret