apiVersion: v1
kind: Pod
metadata:
  name: confmap-inject
spec:
  containers:
  - name: test
    image: rvillaes/spring-boot-app:1.0
    env:
    - name: PROD
      volumeMounts:
      - name: application-config
        mountPath: "/deployments/config"
        readOnly: true
    volumes:
    - name: application-config
      configMap:
        name: spring-app-config
        items:
        - key: credential
          path: application.properties