apiVersion: v1
kind: Pod
metadata:
  name: confmap-inject
spec:
  containers:
  - name: test
    image: rvillaes/spring-boot-app:1.1
    volumeMounts:
    - name: application-config
      mountPath: "/deployments/config"
      readOnly: true
  volumes:
  - name: application-config
    configMap:
      name: app-conf
      items:
      - key: application.properties
        path: application.properties