apiVersion: v1
kind: Pod
metadata:
  name: cm-env-pod
spec:
  containers:
  - name: test
    image: kubernetes/redis:v1
    command: [ "/bin/sh", "-c", "env" ]
    env:
    - name: TEST_LITERAL
      valueFrom:
        configMapKeyRef:
          name: env-conf
          key: conf-key
  restartPolicy: Never