apiVersion: v1
kind: Pod
metadata:
  name: pv-static-pod
spec:
  containers:
  - name: test
    image: nginx
    volumeMounts:
    - mountPath: /test-pv
      name: test-pv
  volumes:
  - name: test-pv
    persistentVolumeClaim:
      claimName: gce-static-claim
