apiVersion: v1
kind: Pod
metadata:
  name: pv-dynamic-pod
spec:
  containers:
  - name: pv-container
    image: nginx
    volumeMounts:
    - mountPath: /test-pv
      name: test-pv
  volumes:
  - name: test-pv
    persistentVolumeClaim:
      claimName: gce-dynamic-claim
