apiVersion: v1
kind: Pod
metadata:
  name: alpine-curl
spec:
  containers:
  - name: alpine-curl
    image: byrnedo/alpine-curl:latest
    command:
      - /bin/sh
      - "c"
      - "sleep 60m"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always