apiVersion: v1
kind: Pod
metadata:
  name: secret-envvar-pod
spec:
  containers:
  - name: pv-container
    image: nginx
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
  restartPolicy: never