apiVersion: v1
kind: Pod
metadata:
  name: cm-env-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.7.9
    command: [ "/bin/sh", "-c", "env" ]
    env:
    - name: TEST_LITERAL
      valueFrom:
        configMapKeyRef:
          name: pwd-secret
          key: db-pwd
  restartPolicy: Never