apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
spec:
  containers:
  - name: pv-container
    image: nginx
    volumeMounts:
    - mountPath: "/etc/secret"
      name: test-secret
      readOnly: true
  volumes:
  - name: test-secret
    secret:
      secretName: mysecret
