apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: test
    image: nginx
    volumeMounts:
    - mountPath: /hp-mnt
      name: hp-volume
  volumes:
  - name: hp-volume
    hostPath:
      path: /hp-volume