apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gce
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  gcePersistentDisk:
    pdName: gce-disk
    fsType: ext4
